
DROP TABLE IF EXISTS BOOK_AUTHOR, BOOK, USER, RESERVATION, LIBRARY;

-- CREATE TABLE BOOK_AUTHOR(
-- id int AUTO_INCREMENT PRIMARY KEY,
-- author_Name varchar(100)
-- );
--
-- CREATE TABLE BOOK(
-- id int AUTO_INCREMENT PRIMARY KEY,
-- title varchar(100),
-- author int ,
-- genre int,
-- copies int,
-- foreign key (author) references BOOK_AUTHOR(id)
-- );
--
-- CREATE TABLE USER(
-- id int AUTO_INCREMENT PRIMARY KEY,
-- user_name varchar(100),
-- password varchar(100)
-- );
--
-- CREATE TABLE RESERVATION(
-- id int AUTO_INCREMENT PRIMARY KEY,
-- book int,
-- user int ,
-- date date,
-- returned BOOLEAN,
-- foreign key (book) references BOOK(id),
-- foreign key (user) references USER(id)
-- );